services:
  mysql:
    image: 'mysql:latest'
    environment:
      MYSQL_DATABASE: gamify_gym
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - '53421:3306'
